install.packages('downloader')
library(downloader)
fileurl<-'https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip'
download(fileurl,dest='data.zip',mode='wb')
unzip('data.zip',exdir = './data')
setwd('./data')
dir(recursive = TRUE)
setwd('./UCI HAR Dataset')
labels<-read.table('./activity_labels.txt')
dim(labels)
labels
features<-read.table('./features.txt')
dim(features)
str(features)
test_sub<-read.table('./test/subject_test.txt')
dim(test_sub)
str(test_sub)
table(test_sub$V1)
test_data<-read.table('./test/X_test.txt')
dim(test_data)
str(test_data,list.len=10)
test_activity<-read.table('./test/y_test.txt')
dim(test_activity)
str(test_activity)
table(test_activity$V1)
train_sub<-read.table('./train/subject_train.txt')
dim(train_sub)
str(train_sub)
table(train_sub$V1)
train_data<-read.table('./train/X_train.txt')
dim(train_data)
str(train_data,list.len=10)
train_activity<-read.table('./train/y_train.txt')
dim(train_activity)
str(train_activity)
table(train_activity$V1)
test<-cbind(test_sub,test_activity,test_data)
train<-cbind(train_sub,train_activity,train_data)
merged<-rbind(test,train)
colnames(merged)<-c('subject','activity',features$V2)
index<-grep('mean\\(\\)|std\\(\\)',features$V2)
library(dplyr)
extracted<-select(merged,c('subject','activity',index+2))
extracted$activity<-labels$V2[extracted$activity]
table(sapply(extracted, function(x){sum(is.na(x))}))
grouped<-group_by(extracted,subject,activity)
summarised<-summarise_each(grouped,funs = mean)
write.table(summarised,file='tidy.txt',row.names = FALSE)